# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reflo < Formula
  desc "Reflo – Reflect, Flow, and Log your daily actions."
  homepage "https://github.com/saijo-shota-biz/reflo"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/saijo-shota-biz/reflo/releases/download/v1.0.0/reflo_1.0.0_darwin_amd64.tar.gz"
      sha256 "5b688252b0d82033fcb6b905768a60ebc4f478e011e3d45d04cd11d5176ed328"

      def install
        bin.install "reflo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/saijo-shota-biz/reflo/releases/download/v1.0.0/reflo_1.0.0_darwin_arm64.tar.gz"
      sha256 "3d36ddc467925a06f4a4adf49718fda77d02ecf11c6be43fd4b1a055cdaf4827"

      def install
        bin.install "reflo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/saijo-shota-biz/reflo/releases/download/v1.0.0/reflo_1.0.0_linux_amd64.tar.gz"
      sha256 "57074fcb8c4bc573117a6e5840afac508e6b835677396e5f482e95f9229a1583"
      def install
        bin.install "reflo"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/saijo-shota-biz/reflo/releases/download/v1.0.0/reflo_1.0.0_linux_arm64.tar.gz"
      sha256 "54d7c87c3dde90ac0646867c951b39fd83d4f6e15b57785ece796b7f83b73968"
      def install
        bin.install "reflo"
      end
    end
  end
end
