# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reflo < Formula
  desc "Reflo – Reflect, Flow, and Log your daily actions."
  homepage "https://github.com/saijo-shota-biz/reflo"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/saijo-shota-biz/reflo/releases/download/v0.1.0/reflo_0.1.0_darwin_amd64.tar.gz"
      sha256 "25e4565961da0d9ace34523da474846dad08dac5e24bed223f03a1945a5777c9"

      def install
        bin.install "reflo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/saijo-shota-biz/reflo/releases/download/v0.1.0/reflo_0.1.0_darwin_arm64.tar.gz"
      sha256 "4ab77d8c7356bcc83a1454fdc66682c43b387f78a080fc717955e8f0f68bbe75"

      def install
        bin.install "reflo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/saijo-shota-biz/reflo/releases/download/v0.1.0/reflo_0.1.0_linux_amd64.tar.gz"
        sha256 "24fc727534aeeba95be0f33f6351273a53c9b240f48ba56b14c89027e19e45f9"

        def install
          bin.install "reflo"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/saijo-shota-biz/reflo/releases/download/v0.1.0/reflo_0.1.0_linux_arm64.tar.gz"
        sha256 "81b886d7d852d0596076c503c2b804273d217bceb95a40f69864a86d97f5a5fe"

        def install
          bin.install "reflo"
        end
      end
    end
  end
end
