# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reflo < Formula
  desc "Reflo – Reflect, Flow, and Log your daily actions."
  homepage "https://github.com/saijo-shota-biz/reflo"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/saijo-shota-biz/reflo/releases/download/v0.1.0/reflo_0.1.0_darwin_amd64.tar.gz"
      sha256 "2e1f5f09edc9f5902bdfe5de03267ff8867323c7b98ddfb71c4c1369f538a514"

      def install
        bin.install "reflo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/saijo-shota-biz/reflo/releases/download/v0.1.0/reflo_0.1.0_darwin_arm64.tar.gz"
      sha256 "ce4ecf5f099d44da3c338b319b65477653160e673876999b48df5d4c5dfd7f1c"

      def install
        bin.install "reflo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/saijo-shota-biz/reflo/releases/download/v0.1.0/reflo_0.1.0_linux_amd64.tar.gz"
        sha256 "53bfc8f4bd259a8bc7a33cf64f9a58b293cdf2c681c73adb9fe17d5457977091"

        def install
          bin.install "reflo"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/saijo-shota-biz/reflo/releases/download/v0.1.0/reflo_0.1.0_linux_arm64.tar.gz"
        sha256 "07a0460548474e0b5bfa2a875771520d7f92a176299ced68f383bc27e0caaeb2"

        def install
          bin.install "reflo"
        end
      end
    end
  end
end
